version: "3"
services:
  imperial_admin:
    build:
      dockerfile: "Dockerfile"
      context: "."
    container_name: imperial_admin
    volumes:
      - ./build:/app/build
    restart: unless-stopped
    # ports:
    #   - 4000:4000
    networks:
      - default
networks:
  default:
    external:
      name: Imperialx
